import type { NextPage } from "next";
import Head from "next/head";
import { useMoralis } from "react-moralis";
import { Login, HomePage } from "../src/core-ui/coreUIIndex";

const Home: NextPage = () => {
  const { isAuthenticated, isInitializing } = useMoralis();
  return (
    <div className="h-screen">
      <Head>
        <title>Web3 Chat App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!isAuthenticated ? (
        <Login />
      ) : isInitializing ? (
        <h1>Loading</h1>
      ) : (
        <HomePage />
      )}
    </div>
  );
};

export default Home;
